#!/usr/bin/perl

use warnings;
use strict;

my %metadata;

# Chomp ?

# What about Windows and Mac end of lines.

while (<>) {
	print;
	my $is_comment   = /^#/  ;
	my $is_metadata  = /^##/ ;
	if ($is_metadata) {
		/^##\s?(\w)\s?=\s?(.+)$/;
		my $field_name =    $1;
		my $field_content = $2;
	}
	unless ($is_metadata | $is_comment) {
		my @column_names = split(/\t/);
}

#warn if it does not contain the mandatory headers ?
#regression tests
